name: condapkg
channels:
- conda-forge
dependencies:
- certifi=2018.1.18=py35_0
- pip=9.0.1=py35_1
- python=3.5.5=0
- setuptools=38.5.1=py35_0
- vs2015_runtime=14.0.25420=0
- wheel=0.30.0=py35_2
- wincertstore=0.2=py35_0
- pip:
  - flask==0.12.2
  - flask-sqlalchemy==2.3.2
  - matplotlib==2.1.2
  - numpy==1.14.0
  - pandas==0.22.0
  - psycopg2==2.7.4
  - python-dateutil==2.6.1
  - scikit-learn==0.19.1
  - scipy==1.0.0
